#!/bin/bash

# Simulate user registration
curl -X POST https://cloud.advancedanimus.com/register -d "username=generalzod&password=kneel"

# Simulate user login
curl -X POST https://cloud.advancedanimus.com/login -d "username=zod&password=beforezod"

# Simulate file upload
curl -X POST https://cloud.advancedanimus.com/upload -F "file=@/path/to/file.txt"

# Simulate file download
curl -O https://cloud.advancedanimus.com/download/file.txt

# Simulate creating a folder
curl -X POST https://cloud.advancedanimus.com/create-folder -d "foldername=kryptonian1"

# Simulate sharing a folder
curl -X POST https://cloud.advancedanimus.com/share-folder -d "foldername=TestFolder&sharewith=user2"
